### ISSUE TITLE
Adding more zipcodes in Heroku table

### ISSUE THREAD

**Issue by martindaniel4** [cathychen95/airbnb-calculator#5]
Hey @cathychen95, @HeLiHarvard, 

Hope you are doing well ! 

I am looking at your app (awesome work) to see how we can add more features. 

One thing I am interested in is adding more polygons to the map. I understand that you have a model [defined here](https://github.com/cathychen95/airbnb-calculator/blob/master/calculator/models.py#L12) that gives all boundaries of the polygon : 

```
      id  zipcode        lat        lng  order_in_boundary
0      1    20001  38.897301 -77.027187                  0
1      2    20001  38.910974 -77.027187                  1
2      3    20001  38.928749 -77.027529                  2
3      4    20001  38.926698 -77.009071                  3
4      5    20001  38.891832 -77.008045                  4
5      6    20001  38.897301 -77.027187                  5
```

Do you remember the source you used for this table ? 

Thanks! 

Martin

**Comment by HeLiHarvard** [comment]
Hey @martindaniel4 ,

The data I used came from https://fusiontables.google.com/DataSource?docid=1Lae-86jeUDLmA6-8APDDqazlTOy1GsTXh28DAkw#rows:id=1

If you export part of the table as a CSV, there should be a script in the repo that I wrote that will take that CSV and upload the boundaries into the database:
calculator/management/commands/convert_fustiontable_to_model.py

Hope this helps!

He

**Comment by martindaniel4** [comment]
Awesome, thanks !
